### ISSUE TITLE
Make sure included statement is corrected in 3.3

### ISSUE THREAD

**Issue by canyon289** [canyon289/bayesian-model-evaluation#22]
**Note in the paper, it says Rhat "estimates the factor by which the scale of the current distribution for $\theta$ might be reduced. What does this mean specifically?**

**Comment by aloctavodia** [comment]
We solved this on slack, right?

**Comment by canyon289** [comment]
Yes! I just need to double check I've updated the text

**Comment by canyon289** [comment]
Copying from slack
Is a measure of how much you are underestimating the variance of a parameter, or inversely how much the variance will reduce ~once~ as the number of samples approach infinity

**Comment by canyon289** [comment]
![image](https://user-images.githubusercontent.com/7213793/57987711-29d49400-7a3a-11e9-8009-f9d81d702dd2.png)
