### ISSUE TITLE
Get full review of Section 2

### ISSUE THREAD

**Issue by canyon289** [canyon289/bayesian-model-evaluation#26]
Merging https://github.com/arviz-devs/bayesian-model-evaluation/pull/7 so I can reuse radon model for section 4. Still need to get double check

In particular need animation of MCMC

**Comment by canyon289** [comment]
@ColCarroll If you have time an animation of the sampler would be cool!

**Comment by ColCarroll** [comment]
Should this animation go in [this notebook](https://github.com/arviz-devs/bayesian-model-evaluation/blob/master/notebooks/2_DataStructures/2_Stu_Bayesian_DataStructures.ipynb)?
