### ISSUE TITLE
conda installation does not work unless "--user" flag used

### ISSUE THREAD

**Issue by darioflute** [canyon289/bayesian-model-evaluation#70]
When running "pip install -r requirements.txt" following the 
conda installation as described in the Readme, pip was stopping
with the error:

ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Using the flag "--user", I was able to complete the installation:
pip install -r requirements.txt --user

and run the notebooks.

**Comment by canyon289** [comment]
Thanks for reporting this. Do you know if you already had certifi installed in your environment before running `pip install`?

**Comment by canyon289** [comment]
I removed the version pin here. Hopefully this helps users who already have a version of certifi that will work. Thank you again for reporting!

https://github.com/canyon289/bayesian-model-evaluation/pull/71

**Comment by canyon289** [comment]
Merged PR. Closing
