### ISSUE TITLE
About section 5.2

### ISSUE THREAD

**Issue by rosgori** [canyon289/bayesian-model-evaluation#81]
In the notebook with title **Section 5.2 Model Comparison Activities**, what is the procedure from going from `In [25]:` and `In [26]:` to `In [27]:`? How do you compute `log_trace` and `linear_trace`?

**Comment by canyon289** [comment]
Ah I'm sorry about that. I fixed the notebook and it should be good to go now. PR is here and its been merged to master. Thanks for pointing this out

https://github.com/canyon289/bayesian-model-evaluation/pull/82
